version: "2"

# The sections in this file are ordered in the order presented in https://golangci-lint.run/docs/configuration/.
# The nested fields are ordered alphabetically.

formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/aws/shim-loggers-for-containerd

linters:
  default: none
  enable:
    - errname
    - errorlint
    - forcetypeassert
    - gocritic
    - godot
    - goheader
    - gosec
    - lll
    - misspell
    - nilerr
    - nilnil
    - nolintlint
    - nosprintfhostport
    - paralleltest
    - predeclared
    - revive
    - staticcheck
    - testableexamples
    - unconvert
    - unparam
    - usestdlibvars
    # TODO: Enable wastedassign after https://github.com/sanposhiho/wastedassign/issues/41 is fixed.
    # - wastedassign
    - whitespace
  settings:
    goheader:
      template-path: copyright_header
    gosec:
      config:
        G306: "0o644"
    lll:
      # 145 is just a lax value that does not require too much work to add this check,
      # and we don't want this to be too strict anyway.
      line-length: 145
      tab-width: 4
    makezero:
      always: true
    nolintlint:
      require-explanation: true
      require-specific: true
    paralleltest:
      # Ignore missing calls to `t.Parallel()` and only report incorrect uses of it.
      # Default: false
      ignore-missing: true
    staticcheck:
      checks: ["all", "-ST1003"]
  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - lll
        # A go:generate statement has to be in the same line: https://github.com/golang/go/issues/46050.
        source: "^//go:generate "
