#!/bin/bash
# ecs local endpoint can only use credentials in aws credential file instead of env vars

aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile default
aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile default
aws configure set aws_session_token $AWS_SESSION_TOKEN --profile default
docker run -d --name ecs-local-endpoint -p 51679:51679 \
-v $HOME/.aws/:/home/.aws/ -e AWS_REGION=us-west-2 \
-e HOME="/home" -e AWS_PROFILE=default -e ECS_LOCAL_METADATA_PORT=51679 \
amazon/amazon-ecs-local-container-endpoints
